### ISSUE TITLE
Question: “Generating multiple theme files at once”

### ISSUE THREAD

**Issue by olegafx** [andywer/postcss-theme#3]
Is it possible to generate multiple css theme-files with 1 webpack build?

Pseudocode example:

**Input**

```
colors-black.css
@var primaryColor: rgba(0, 0, 0, 1);
```

```
colors-blue.css
@var primaryColor: rgba(0, 174, 239, 1);
```

```
colors-red.css
@var primaryColor: rgba(222, 0, 0, 1);
```

```
module.css
.button {
  color: primaryColor;
}
```

**Output**

```
style-black.css
.button {
  color: rgba(0, 0, 0, 1);
}
```

```
style-blue.css
.button {
  color: rgba(0, 174, 239, 1);
}
```

```
style-red.css
.button {
  color: rgba(222, 0, 0, 1);
}
```

Btw, thanks for your work.

**Comment by andywer** [comment]
Hi @olegafx!

My first question would be if it's really necessary to create all these static files with resolved variables.
But if you do... I don't have any immediate solution for a webpack-based app at hand. You could quite easily do it using a JS script calling `postcss` directly. But I guess you would rather prefer letting webpack do it.

I will think about it, though.

PS: Maybe you can provide some sample or explanation of your setting? Usually in webpack you would have an `import './module.css'` in some JS file to include the style. Maybe something like this would be useful: `import './module.css!postcss?theme=red'`

**Comment by olegafx** [comment]
I'm using `css-modules` with `postcss-loader`. I need these static files to solve 1 problem in a really dirty way: dynamic site themes without moving css to js (`Radium`, …). At least as a temporary solution… 😄

**Comment by andywer** [comment]
I can feel your pain ^^. I thought about it, but still got no nice solution. Maybe you can add an additional entry point per file in your webpack config, like https://webpack.github.io/docs/multiple-entry-points.html

Didn't try it, but that could possibly work...

**Comment by olegafx** [comment]
Ok, I’ll try something. Thanks 😎

**Comment by andywer** [comment]
PS: Hi @olegafx! Did it work?

PPS: You could also configure the plugin like this:
`postcssTheme({ themePath: process.env.THEME_PATH })`
and run webpack multiple times with `THEME_PATH=./path/to/theme npm run build` ;)

**Comment by olegafx** [comment]
I didn't try that yet :)

**Comment by olegafx** [comment]
@andywer We decided to use css-variables for modern browsers and generate static css file for old browsers using [postcss-css-variables](https://github.com/MadLittleMods/postcss-css-variables)

**Comment by firasdib** [comment]
@olegafx How did you sort this one out for the older browsers?

**Comment by andywer** [comment]
Suggestion what you could do using postcss-theme and webpack:

In your webpack config:

``` js
  postcssTheme({
    themePath: 'path/to/themes/' + process.env.THEME
  })
```

Then run

``` sh
THEME=some-theme webpack --config my.webpack.config
```

**Comment by firasdib** [comment]
@andywer That works I suppose, but if I have several themes that means I have to run that multiple times to generate those files, at which point I would just write a small script to do it. I'm generally looking for an all around solution I can use to generate those files without too much extra script-writing. Another nut I'll have to crack is how to couple this with style/css loader during dev/prod. Ugh.

**Comment by firasdib** [comment]
I went ahead and posted my question to SO in hope someone would be able to help me: http://stackoverflow.com/questions/38963277/webpack-postcss-themes-hot-reloading

**Comment by calvinwyoung** [comment]
@firasdib I'm running into the exact same problem you described here and on SO. Have you come up with a better solution in the last few months?

**Comment by firasdib** [comment]
@calvinwyoung Not really. I just brute forced it like in `solution 1` in my S.O. post

**Comment by ctaepper** [comment]
as for running the build multiple times: webpack config can also export an array of configs, so this should work

```javascript
const themes = ['theme1', 'theme2']
module.exports = themes.map((theme) => {
  // return webpack config
  return {
    // ...
    postcssTheme({
      themePath: 'path/to/themes/' + theme
    })
    // ...
  }
})
```
you will also have to use the extract text plugin to create different css file names for each theme

**Comment by calvinwyoung** [comment]
@firasdib Makes sense — I was hoping there might be a better solution now. I'll post on this thread and SO if I come across anything better.

@ctaepper Ah that's awesome, that should get us a little closer to what we're looking for. Thank you!

**Comment by terence55** [comment]
I'm dealing with the similar problem currently, I try to figure it out without any invasive of codes. Then I write a webpack plugin [themes-switch](https://github.com/terence55/themes-switch) to do that. Maybe it can help you.
Now I use variables to define different colors and dimensions, then webpack would generate multiple theme files at once, and the style formats can be less, postcss and sass. Then I can make a realtime-switch in my app.

theme-a.less
```
@color-main: #0A6EFA;
@color-text: #000;
```

theme-b.less
```
@color-main: #222A42;
@color-text: #FFF;
```

default.less
```
@import 'theme-a.less';
```

main.less
```
@import 'default.less';
.main {
  background: @color-main;
}
```

Config in webpack
```js
new ThemesGeneratorPlugin({
      srcDir: 'src',
      themesDir: 'src/assets/themes',
      outputDir: 'static/css',
      defaultStyleName: 'default.less',
      themesLoader: {
        test: /\.(less|css)$/,
        loaders: [
          { loader: require.resolve('css-loader') },
          { loader: require.resolve('less-loader') }
        ]
      }
    })
```

In use
```js
changeTheme('theme-b', 'theme-b-123456.css')
```
