### ISSUE TITLE
Provide working webpack example

### ISSUE THREAD

**Issue by garethdown44** [andywer/postcss-theme#5]
Please can you provide a working webpack example?

The webpack example you have on the README is incomplete.

I struggled for a long time trying to get it to work, using the postcss-modules-values and postcss-modules-extract-imports plugins. I tried them in different orders but it just didn't work.

It looks like a great plugin but either it doesn't work or the documentation is not complete.

**Comment by andywer** [comment]
Sorry, @garethdown44! I know there was some unanswered issue somewhere... 🙈

Yeah, this is a good point. In the provided example CSS modules are off and no css-modules-values is there. Should probably require using CSS modules for now.

Try this in your webpack config:

``` js
import theme from 'postcss-theme'

module.exports = {
  module: {
    loaders: [
      {
        test:   /\.css$/,
        loader: 'style-loader!css-loader?modules!postcss-loader'    // <- `?modules`
      }
    ]
  },
  postcss: function () {
    return [
      theme({ themePath: './path/to/theme' })
    ]
  }
}
```

**Comment by andywer** [comment]
@garethdown44 Did you get it to work?
